<a href="https://colab.research.google.com/github/jsh5879/deep_learning_machine_learning/blob/master/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#titanic
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
import tensorflow as tf
tf.set_random_seed(777)
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import numpy as np

##########데이터 로드

train_df = pd.read_excel('http://june3471.pythonanywhere.com/media/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx', sheet_name='train')
test_df = pd.read_excel('http://june3471.pythonanywhere.com/media/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx', sheet_name='test')

labels = ['death', 'survival']

##########데이터 분석

##########데이터 전처리

x_train_df = train_df.drop(['name', 'ticket', 'survival'], axis=1)
x_test_df = test_df.drop(['name', 'ticket', 'survival'], axis=1)
y_train_df = train_df[['survival']]
y_test_df = test_df[['survival']]

print(x_train_df.head())
print(x_train_df.columns) #Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'], dtype='object')

transformer = make_column_transformer(
    (OneHotEncoder(), ['pclass', 'sex', 'embarked']),
    remainder='passthrough')
transformer.fit(x_train_df)
x_train = transformer.transform(x_train_df)
x_test = transformer.transform(x_test_df)

y_train = y_train_df.values
y_test = y_test_df.values

print(x_train.shape)
print(y_train.shape)

##########모델 학습
##########모델 검증

input = Input(shape=(12,))
net = Dense(units=512, activation='relu')(input)
net = Dense(units=512, activation='relu')(net)
net = Dense(units=1, activation='sigmoid')(input)
model = Model(inputs=input, outputs=net)

model.summary()

model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.01), metrics=['accuracy'])
model.fit(x_train, y_train, epochs=50, validation_data=(x_test, y_test)) 

##########모델 예측

x_test = transformer.transform(pd.DataFrame([[2, 'Female', 21, 0, 1, 21.00, 'S']],
                                                   columns=['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']))
print(x_test) #[[ 0.  1.  0.  1.  0.  0.  0.  1. 21.  0.  1. 21.]]

y_predict = model.predict(x_test)
print(y_predict) #[[0.9948258]]
print(y_predict.flatten())
print(y_predict.flatten()[0])
print(1 if y_predict.flatten()[0] > 0.5 else 0)
print(labels[1 if y_predict.flatten()[0] > 0.5 else 0]) #pass

   pclass     sex  age  sibsp  parch   fare embarked
0       2  Female   17      0      0  12.00        C
1       3  Female   37      0      0   9.59        S
2       3    Male   18      1      1  20.21        S
3       3    Male   30      0      0   7.90        S
4       3    Male   25      0      0   7.65        S
Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'], dtype='object')
(730, 12)
(730, 1)
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 12)]              0         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 13        
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________
Train on 730 samples, validate on 313 samples
Epoch 1/50
730/730 [==============================] - 0s

In [0]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
from google.colab import files
uploaded = files.upload()

Saving test_result.csv to test_result.csv


In [0]:
import pandas as pd    
import numpy as np
                                                      #총 5만개
data_train = pd.read_csv('train.csv')  #훈련          4만개
data_test = pd.read_csv('test.csv')   #검증(테스트)   1만개
data_check = pd.read_csv('test_result.csv')   #정답
#print(data_train)

data_train = data_train.rename(columns = {'Pclass' : 'TicketClass'})
data_test = data_test.rename(columns = {'Pclass' : 'TicketClass'})

data_train = data_train.drop(['Name','Ticket','Fare','Cabin','Embarked','Age'],axis =1)  #axis = 행중심
data_test = data_test.drop(['Name','Age','Ticket','Fare','Cabin','Embarked'], axis =1)
#print(data_train)

#Importing LabelEncoder from Sklearn
from sklearn.preprocessing import LabelEncoder       #원핫인코딩 male = 0, female = 0
label_encoder_sex = LabelEncoder()
#print(data_train.head())
#print(data_test.head())

# Transforming sex column values using label Encoder
data_train.iloc[:,3]  = label_encoder_sex.fit_transform(data_train.iloc[:,3])    #인덱스기준 모든행 3열을 라벨인코디하겠다
data_test.iloc[:,2] = label_encoder_sex.fit_transform(data_test.iloc[:,2])

data_train = data_train[['PassengerId','Sex','SibSp','Parch','TicketClass','Survived']]
data_test = data_test[['PassengerId','Sex','SibSp','Parch','TicketClass']]
print(data_train.head())

X_train = data_train.iloc[:,0:5]   # Inputs
Y_train = data_train.iloc[:,5]     #Output (Survived)
print(X_train.head()) # dataframe 일 경우

from sklearn.preprocessing import StandardScaler  #0~1사이로 스케일링 #https://datascienceschool.net/view-notebook/f43be7d6515b48c0beb909826993c856/
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(data_test)
#numpy디버깅 >> 행, 열로
print(X_train[:5, :])  #[[행, 열]] 일 경우
print(X_test[:5, :])  #[[행, 열]] 일 경우

model = Sequential()
model.add(Dense(13, input_dim=5, activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=10, epochs=10)

# 단순 테스트
pred = np.array([[-1.70305005,  0.75592895, -0.49947002, -0.4002477,  0.87348191]])
print(model.predict(pred))

#getting predictions of test data
prediction = classifier.predict(X_test).tolist()
# list to series
se = pd.Series(prediction)
# creating new column of predictions in data_check dataframe
data_check['check'] = se
data_check['check'] = data_check['check'].str.get(0)

series = []
for val in data_check.check:
    if val >= 0.5:
        series.append(1)
    else:
        series.append(0)
data_check['final'] = series

match = 0
nomatch = 0
for val in data_check.values:
    if val[1] == val[3]:
        match = match +1
    else:
        nomatch = nomatch +1

print('match : ',match)
print('nomatch : ',nomatch)
print('accuracy : ',match/(match + nomatch)*100,'%')

   PassengerId  Sex  SibSp  Parch  TicketClass  Survived
0            1    1      1      0            3         0
1            2    0      1      0            1         1
2            3    0      0      0            3         1
3            4    0      1      0            1         1
4            5    1      0      0            3         0
   PassengerId  Sex  SibSp  Parch  TicketClass
0            1    1      1      0            3
1            2    0      1      0            1
2            3    0      0      0            3
3            4    0      1      0            1
4            5    1      0      0            3
[[-1.73010796  0.73769513  0.43279337 -0.47367361  0.82737724]
 [-1.72622007 -1.35557354  0.43279337 -0.47367361 -1.56610693]
 [-1.72233219 -1.35557354 -0.4745452  -0.47367361  0.82737724]
 [-1.71844431 -1.35557354  0.43279337 -0.47367361 -1.56610693]
 [-1.71455642  0.73769513 -0.4745452  -0.47367361  0.82737724]]
[[-1.72791209  0.75592895 -0.49947002 -0.4002477   0.8734819